#pragma config(Sensor, in1,    potentmeter,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  touch,          sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port6,           ClawMotor,     tmotorVex269, openLoop)
#pragma config(Motor,  port7,           ArmMotor,      tmotorVex269, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program allows your robot to move back and forth, first 0,5m and back then 1m and back and		*|
|*	so on until you reach 2,5m.																																				*|
|*                                                                                                    *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 7        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 10        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/



const int BASETIME=925;

void drive_backward(int i)
{
	motor[rightMotor] = -117;
	motor[leftMotor]  = -127;
	wait1Msec(BASETIME*i);
}

void drive_forward(int i)
{
	motor[rightMotor] = 127;
	motor[leftMotor]  = 107;
	wait1Msec(BASETIME*i);
}

task main()
{
	wait1Msec(2000);
	for(int i = 1; i<6;i++){
		drive_forward(i);
		drive_backward(i);

}
}
