#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex269, openLoop)
#pragma config(Motor,  port7,           udmotor,       tmotorVex269, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                              - Forward for Distance with Encoders -                                *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  The program starts with a while loop that is constantly running so it wont stop ever							*|
|*	the first task is for the motor left and right to go forward when the joystick goes forward or back*|																																																		*|
|*  the second is the if vex thigy wich is saying if the button on the controller is pressed then     *|
|*  this happens ... the clawmotor opens or closes depending on what u chose to press                 *|
|*  the else if is for if the other button is pressed it closes the claw                              *|
|*  then i just copied the last part and revesed  it putting 5 insted of 6 in the Btn6D and Btn6U     *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" model, but may not be needed for all robot configurations.                      *|
|*    2)  Whichever encoder is being used for feedback should be cleared just before it starts        *|
|*        counting by using the "SensorValue(encoder) = 0;".  This helps ensure consistancy.          *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Shaft Encoder     Right side                        *|
|*    Digital - Port 3,4  leftEncoder         VEX Shaft Encoder     Left side                         *|
\*----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{

while(1==1)
{
	motor[rightMotor]=vexRT[Ch2];
	motor[leftMotor]=vexRT[Ch1];

	if(vexRT[Btn6U]==1)
	{
		motor[clawMotor] = 127;

	}
	else if(vexRT[Btn6D]== 1)
	{
		motor[clawMotor]= -127;
	}
	else
	{
	motor[clawMotor]= 0;
	}

	if(vexRT[Btn5U]==1)
	{
		motor[udMotor] = 127;

	}
	else if(vexRT[Btn5D]== 1)
	{
		motor[udMotor]= -127;
	}
	else
	{
	motor[udMotor]= 0;
	}
}


}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
