#pragma config(Sensor, in1,    potentmeter,    sensorPotentiometer)
#pragma config(Sensor, in2,    lightSensor,    sensorReflection)
#pragma config(Sensor, in3,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in4,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in5,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  Button,         sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port2,           armMotor,      tmotorVex269, openLoop)
#pragma config(Motor,  port9,           clawMotor,     tmotorVex269, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex269, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "./myheaders/myhead.h"

#include "./mydrivefunctions/drive.c"

task verk3()
{
	remote();

}
task verk1()
{
	forward();
}
task verk2()
{
	drive_backward(i);
	drive_forward(i);
}
task verk4()
{
	forward2();
}
task verk5()
{
	verkefni5();
}
task verk6()
{
	follow_line(i);
	arm_down();
	arm_up();
	claw_close();
	claw_open();
	turn_around(i);
	stop_motor();

}


task main()
{
	while(vexRT[Btn8D] == 0)
	{
		motor[rightMotor]=vexRT[Ch1];
		motor[leftMotor]=vexRT[Ch2];

		if(vexRT[Btn8R]==1)
		{
			startTask(verk3);

		}
		else if (vexRT[Btn8L]==1)
		{
			startTask(verk1);
		}
		else if (vexRT[Btn8U]==1)
		{
			startTask(verk2);

		}
		else if (vexRT[Btn7L]==1)
		{
			wait1Msec(2000);
			for(int i = 1; i<6;i++){
				drive_forward(i);
				drive_backward(i);
				}
		}
		else if (vexRT[Btn7U]==1)
		{
			startTask(verk4);

		}
		else if (vexRT[Btn7R]==1)
		{
			StartTask(verk5)
		}
		else if (vexRT[Btn7D]==1)
		{
			while (SensorValue(sonarSensor) >= 19)
			{
				follow_line(i);
			}
			stop_motor();
			claw_open();
			arm_down();
			claw_close();
			arm_up();
			stop_motor();
			turn_around(i);
			stop_motor();
			follow_line(i);




				}
		}
	}
